//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.21 at 08:57:27 PM MSK 
//


package ru.digitalspirit.rosnfo.model.brk.model;

import java.math.BigInteger;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Клиент
 * 
 * <p>Java class for Customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="CustomerID" type="{http://NFOCommon.NFO.ru}CustomerIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Branch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OfficialName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="BirthPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Scope" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResidentFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ResidentCountryID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INNDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="NameENG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SNILS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VipeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailList" type="{http://NFOCommon.NFO.ru}EmailType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhoneList" type="{http://NFOCommon.NFO.ru}PhoneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddressList" type="{http://NFOCommon.NFO.ru}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Document" type="{http://Document.NFO.ru}Document" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedPerson" type="{http://RelatedPerson.NFO.ru}RelatedPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CustomerApproover" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerApprooverFIO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerChecker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerCheckerFIO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SegmentCRM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CRMClientStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tariff" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TariffPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TariffPlanCRM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KYCId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KYCDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="KYCNextDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="KYCStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KYCSRStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KYCComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubSegment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Customer", namespace = "http://Customer.NFO.ru", propOrder = {
    "id",
    "customerID",
    "branch",
    "department",
    "type",
    "customerType",
    "fullName",
    "officialName",
    "nameLat",
    "shortName",
    "lastName",
    "firstName",
    "middleName",
    "birthDate",
    "birthPlace",
    "scope",
    "residentFlag",
    "residentCountryID",
    "clientLocation",
    "inn",
    "innDate",
    "nameENG",
    "sex",
    "snils",
    "vipeCode",
    "emailList",
    "phoneList",
    "addressList",
    "document",
    "relatedPerson",
    "customerApproover",
    "customerApprooverFIO",
    "customerChecker",
    "customerCheckerFIO",
    "bic",
    "segment",
    "segmentCRM",
    "crmClientStatus",
    "tariff",
    "tariffPlan",
    "tariffPlanCRM",
    "kycId",
    "kycDate",
    "kycNextDate",
    "kycStatus",
    "kycsrStatus",
    "kycComment",
    "group",
    "subSegment"
})
public class Customer {

    protected BigInteger id;
    @XmlElement(name = "CustomerID")
    protected List<CustomerIDType> customerID;
    @XmlElement(name = "Branch")
    protected String branch;
    @XmlElement(name = "Department")
    protected String department;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "CustomerType")
    protected String customerType;
    @XmlElement(name = "FullName")
    protected String fullName;
    @XmlElement(name = "OfficialName")
    protected String officialName;
    @XmlElement(name = "NameLat")
    protected String nameLat;
    @XmlElement(name = "ShortName")
    protected String shortName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "BirthDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date birthDate;
    @XmlElement(name = "BirthPlace")
    protected String birthPlace;
    @XmlElement(name = "Scope")
    protected String scope;
    @XmlElement(name = "ResidentFlag")
    protected Boolean residentFlag;
    @XmlElement(name = "ResidentCountryID")
    protected String residentCountryID;
    @XmlElement(name = "ClientLocation")
    protected String clientLocation;
    @XmlElement(name = "INN")
    protected String inn;
    @XmlElement(name = "INNDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date innDate;
    @XmlElement(name = "NameENG")
    protected String nameENG;
    @XmlElement(name = "Sex")
    protected String sex;
    @XmlElement(name = "SNILS")
    protected String snils;
    @XmlElement(name = "VipeCode")
    protected String vipeCode;
    @XmlElement(name = "EmailList")
    protected List<EmailType> emailList;
    @XmlElement(name = "PhoneList")
    protected List<PhoneType> phoneList;
    @XmlElement(name = "AddressList")
    protected List<AddressType> addressList;
    @XmlElement(name = "Document")
    protected List<Document> document;
    @XmlElement(name = "RelatedPerson")
    protected List<RelatedPerson> relatedPerson;
    @XmlElement(name = "CustomerApproover")
    protected String customerApproover;
    @XmlElement(name = "CustomerApprooverFIO")
    protected String customerApprooverFIO;
    @XmlElement(name = "CustomerChecker")
    protected String customerChecker;
    @XmlElement(name = "CustomerCheckerFIO")
    protected String customerCheckerFIO;
    @XmlElement(name = "BIC")
    protected String bic;
    @XmlElement(name = "Segment")
    protected String segment;
    @XmlElement(name = "SegmentCRM")
    protected String segmentCRM;
    @XmlElement(name = "CRMClientStatus")
    protected String crmClientStatus;
    @XmlElement(name = "Tariff")
    protected Boolean tariff;
    @XmlElement(name = "TariffPlan")
    protected String tariffPlan;
    @XmlElement(name = "TariffPlanCRM")
    protected String tariffPlanCRM;
    @XmlElement(name = "KYCId")
    protected String kycId;
    @XmlElement(name = "KYCDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date kycDate;
    @XmlElement(name = "KYCNextDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date kycNextDate;
    @XmlElement(name = "KYCStatus")
    protected String kycStatus;
    @XmlElement(name = "KYCSRStatus")
    protected String kycsrStatus;
    @XmlElement(name = "KYCComment")
    protected String kycComment;
    @XmlElement(name = "Group")
    protected String group;
    @XmlElement(name = "SubSegment")
    protected String subSegment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerIDType }
     * 
     * 
     */
    public List<CustomerIDType> getCustomerID() {
        if (customerID == null) {
            customerID = new ArrayList<CustomerIDType>();
        }
        return this.customerID;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the officialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * Sets the value of the officialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialName(String value) {
        this.officialName = value;
    }

    /**
     * Gets the value of the nameLat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLat() {
        return nameLat;
    }

    /**
     * Sets the value of the nameLat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLat(String value) {
        this.nameLat = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(Date value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the residentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getResidentFlag() {
        return residentFlag;
    }

    /**
     * Sets the value of the residentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResidentFlag(Boolean value) {
        this.residentFlag = value;
    }

    /**
     * Gets the value of the residentCountryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentCountryID() {
        return residentCountryID;
    }

    /**
     * Sets the value of the residentCountryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentCountryID(String value) {
        this.residentCountryID = value;
    }

    /**
     * Gets the value of the clientLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientLocation() {
        return clientLocation;
    }

    /**
     * Sets the value of the clientLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientLocation(String value) {
        this.clientLocation = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the innDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getINNDate() {
        return innDate;
    }

    /**
     * Sets the value of the innDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINNDate(Date value) {
        this.innDate = value;
    }

    /**
     * Gets the value of the nameENG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameENG() {
        return nameENG;
    }

    /**
     * Sets the value of the nameENG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameENG(String value) {
        this.nameENG = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNILS() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNILS(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the vipeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVipeCode() {
        return vipeCode;
    }

    /**
     * Sets the value of the vipeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVipeCode(String value) {
        this.vipeCode = value;
    }

    /**
     * Gets the value of the emailList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailType }
     * 
     * 
     */
    public List<EmailType> getEmailList() {
        if (emailList == null) {
            emailList = new ArrayList<EmailType>();
        }
        return this.emailList;
    }

    /**
     * Gets the value of the phoneList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneType }
     * 
     * 
     */
    public List<PhoneType> getPhoneList() {
        if (phoneList == null) {
            phoneList = new ArrayList<PhoneType>();
        }
        return this.phoneList;
    }

    /**
     * Gets the value of the addressList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddressList() {
        if (addressList == null) {
            addressList = new ArrayList<AddressType>();
        }
        return this.addressList;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document }
     * 
     * 
     */
    public List<Document> getDocument() {
        if (document == null) {
            document = new ArrayList<Document>();
        }
        return this.document;
    }

    /**
     * Gets the value of the relatedPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPerson }
     * 
     * 
     */
    public List<RelatedPerson> getRelatedPerson() {
        if (relatedPerson == null) {
            relatedPerson = new ArrayList<RelatedPerson>();
        }
        return this.relatedPerson;
    }

    /**
     * Gets the value of the customerApproover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerApproover() {
        return customerApproover;
    }

    /**
     * Sets the value of the customerApproover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerApproover(String value) {
        this.customerApproover = value;
    }

    /**
     * Gets the value of the customerApprooverFIO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerApprooverFIO() {
        return customerApprooverFIO;
    }

    /**
     * Sets the value of the customerApprooverFIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerApprooverFIO(String value) {
        this.customerApprooverFIO = value;
    }

    /**
     * Gets the value of the customerChecker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerChecker() {
        return customerChecker;
    }

    /**
     * Sets the value of the customerChecker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerChecker(String value) {
        this.customerChecker = value;
    }

    /**
     * Gets the value of the customerCheckerFIO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCheckerFIO() {
        return customerCheckerFIO;
    }

    /**
     * Sets the value of the customerCheckerFIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCheckerFIO(String value) {
        this.customerCheckerFIO = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the segmentCRM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentCRM() {
        return segmentCRM;
    }

    /**
     * Sets the value of the segmentCRM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentCRM(String value) {
        this.segmentCRM = value;
    }

    /**
     * Gets the value of the crmClientStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRMClientStatus() {
        return crmClientStatus;
    }

    /**
     * Sets the value of the crmClientStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRMClientStatus(String value) {
        this.crmClientStatus = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTariff(Boolean value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the tariffPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffPlan() {
        return tariffPlan;
    }

    /**
     * Sets the value of the tariffPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffPlan(String value) {
        this.tariffPlan = value;
    }

    /**
     * Gets the value of the tariffPlanCRM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffPlanCRM() {
        return tariffPlanCRM;
    }

    /**
     * Sets the value of the tariffPlanCRM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffPlanCRM(String value) {
        this.tariffPlanCRM = value;
    }

    /**
     * Gets the value of the kycId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCId() {
        return kycId;
    }

    /**
     * Sets the value of the kycId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCId(String value) {
        this.kycId = value;
    }

    /**
     * Gets the value of the kycDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getKYCDate() {
        return kycDate;
    }

    /**
     * Sets the value of the kycDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCDate(Date value) {
        this.kycDate = value;
    }

    /**
     * Gets the value of the kycNextDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getKYCNextDate() {
        return kycNextDate;
    }

    /**
     * Sets the value of the kycNextDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCNextDate(Date value) {
        this.kycNextDate = value;
    }

    /**
     * Gets the value of the kycStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCStatus() {
        return kycStatus;
    }

    /**
     * Sets the value of the kycStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCStatus(String value) {
        this.kycStatus = value;
    }

    /**
     * Gets the value of the kycsrStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCSRStatus() {
        return kycsrStatus;
    }

    /**
     * Sets the value of the kycsrStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCSRStatus(String value) {
        this.kycsrStatus = value;
    }

    /**
     * Gets the value of the kycComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCComment() {
        return kycComment;
    }

    /**
     * Sets the value of the kycComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCComment(String value) {
        this.kycComment = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the subSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSegment() {
        return subSegment;
    }

    /**
     * Sets the value of the subSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSegment(String value) {
        this.subSegment = value;
    }

    public void setCustomerID(List<CustomerIDType> value) {
        this.customerID = value;
    }

    public void setEmailList(List<EmailType> value) {
        this.emailList = value;
    }

    public void setPhoneList(List<PhoneType> value) {
        this.phoneList = value;
    }

    public void setAddressList(List<AddressType> value) {
        this.addressList = value;
    }

    public void setDocument(List<Document> value) {
        this.document = value;
    }

    public void setRelatedPerson(List<RelatedPerson> value) {
        this.relatedPerson = value;
    }

}
